export TEST := test
export PRINTF := printf
export RM := rm
export FIND := find
export GCC := gcc
XML_CONF := xml2-config

export CFLAGS = $(shell $(XML_CONF) --cflags) -Wall -Werror -g
export INCLUDES = $(shell $(XML_CONF) --libs) -lcurl -lcrypto -lconfig
